(function(){"use strict";
const C=window.HALLOWEEN_CONFIG,API="https://api.weather.gov",$=id=>document.getElementById(id);
const state={observations:"loading",forecast:"loading",alerts:"loading",afd:"loading",waits:"loading"};\nlet waitHistory={};
let selectedVenue=C.venues[0],selectedDate=null,forecastCache=new Map();
const fmt=(d,o={})=>new Intl.DateTimeFormat("en-US",{timeZone:C.timezone,...o}).format(d);
const dateKey=d=>fmt(d,{year:"numeric",month:"2-digit",day:"2-digit"}).replace(/(\d+)\/(\d+)\/(\d+)/,"$3-$1-$2");
const localDate=(key,hour=0)=>new Date(new Date(key+"T00:00:00-04:00").getTime()+hour*3600000);
const request=url=>fetch(url,{headers:{Accept:"application/geo+json"},cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(r.status+" "+r.statusText);return r.json()});
const cToF=v=>v==null?null:v*9/5+32,kmhToMph=v=>v==null?null:v*.621371,mToMi=v=>v==null?null:v*.000621371,round=v=>v==null?null:Math.round(v);
const safe=(v,f="—")=>v==null||Number.isNaN(v)?f:v;
const compass=deg=>deg==null?"VRB":["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"][Math.round(deg/22.5)%16];
function isEvent(v,key){if(v.dates.includes(key))return true;if(!v.dateRule)return false;const d=localDate(key,12),r=v.dateRule;return key>=r.from&&key<=r.to&&r.weekdays.includes(d.getDay())}
function nextEvent(v,from=new Date()){for(let i=0;i<70;i++){const d=new Date(from);d.setDate(d.getDate()+i);const k=dateKey(d);if(isEvent(v,k))return k}return null}
function eventHours(v,key){return Array.from({length:v.endHour-v.startHour+1},(_,i)=>localDate(key,v.startHour+i))}
function age(date){const minutes=Math.max(0,Math.floor((Date.now()-date.getTime())/60000));return{minutes,level:minutes<C.freshnessMinutes.current?"current":minutes<=C.freshnessMinutes.stale?"late":"stale"}}
function updateSystem(){const a=Object.values(state);let s=a.every(x=>x==="failed")?"offline":a.some(x=>x==="failed")?"degraded":a.some(x=>x==="stale")?"stale":a.some(x=>x==="loading")?"loading":"current";$("system-state").textContent=s.toUpperCase();$("system-state").className="state "+s;$("last-refresh").textContent="LAST CHECK "+fmt(new Date(),{hour:"numeric",minute:"2-digit",second:"2-digit"})}
function tick(){const n=new Date();$("local-date").textContent=fmt(n,{weekday:"short",month:"short",day:"numeric",year:"numeric"}).toUpperCase();$("local-clock").textContent=fmt(n,{hour:"numeric",minute:"2-digit",second:"2-digit"})}
function setup(){
 $("venue-tabs").innerHTML=C.venues.map((v,i)=>'<button data-id="'+v.id+'" class="'+(i===0?"active":"")+'">'+v.short+"<small>"+v.event+"</small></button>").join("");
 $("venue-tabs").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>selectVenue(b.dataset.id)));
 $("quick-links").innerHTML=C.links.map(l=>'<a href="'+l.url+'" target="_blank" rel="noopener">'+l.label+"</a>").join("");
 tick();setInterval(tick,1000);selectVenue(selectedVenue.id);loadObservations();loadAfd();loadWaitTimes();
 setInterval(loadObservations,C.refreshMs.observations);setInterval(()=>loadSelected(true),C.refreshMs.forecast);setInterval(loadAlerts,C.refreshMs.alerts);setInterval(loadAfd,C.refreshMs.afd);setInterval(loadWaitTimes,300000);
 document.addEventListener("visibilitychange",()=>{if(!document.hidden){loadObservations();loadSelected(true);loadAlerts();loadAfd();loadWaitTimes()}});
}
function selectVenue(id){selectedVenue=C.venues.find(v=>v.id===id);$("venue-tabs").querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.id===id));$("wait-panel").classList.toggle("hidden",id!=="universal");selectedDate=nextEvent(selectedVenue)||dateKey(new Date());$("venue-name").textContent=selectedVenue.name;renderEventDetail();renderDateStrip();loadSelected();loadAlerts();if(id==="universal")loadWaitTimes()}
function renderEventDetail(){const event=isEvent(selectedVenue,selectedDate);$("event-label").textContent=event?"SELECTED EVENT NIGHT":"NON-EVENT DATE";$("event-detail").innerHTML=event?selectedVenue.event+" · "+fmt(localDate(selectedDate,12),{weekday:"long",month:"short",day:"numeric"})+' · <a href="'+selectedVenue.officialUrl+'" target="_blank" rel="noopener">VERIFY EVENT HOURS</a>':"Daily planning forecast · "+fmt(localDate(selectedDate,12),{weekday:"long",month:"long",day:"numeric"})}
function nextSeven(){const out=[];for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()+i);out.push(dateKey(d))}const n=nextEvent(selectedVenue);if(n&&!out.includes(n)&&n>out[6])out[6]=n;return out}
function renderDateStrip(){const keys=nextSeven();if(!keys.includes(selectedDate))selectedDate=keys.find(k=>isEvent(selectedVenue,k))||keys[0];$("date-strip").innerHTML=keys.map(k=>'<button class="date-card '+(k===selectedDate?"active":"")+'" data-date="'+k+'"><time>'+fmt(localDate(k,12),{weekday:"short",month:"short",day:"numeric"}).toUpperCase()+'</time><small class="'+(isEvent(selectedVenue,k)?"event-mark":"")+'">'+(isEvent(selectedVenue,k)?"● EVENT NIGHT":"DAILY OUTLOOK")+"</small></button>").join("");$("date-strip").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selectedDate=b.dataset.date;renderDateStrip();renderEventDetail();loadSelected()}))}
async function getForecast(v,force=false){if(!force&&forecastCache.has(v.id))return forecastCache.get(v.id);const point=await request(API+"/points/"+v.latitude+","+v.longitude);const [grid,hourly,daily]=await Promise.all([request(point.properties.forecastGridData),request(point.properties.forecastHourly),request(point.properties.forecast)]);const data={grid:grid.properties,hourly:hourly.properties?.periods||[],daily:daily.properties?.periods||[]};forecastCache.set(v.id,data);return data}
function parseDuration(t){const m=t.match(/P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?)?/);return((+(m?.[1]||0)*24+ +(m?.[2]||0))*60+ +(m?.[3]||0))*60000}
function gridAt(series,time){if(!series?.values)return null;const target=time.getTime();for(const x of series.values){const [s,d="PT1H"]=x.validTime.split("/"),start=new Date(s).getTime();if(target>=start&&target<start+parseDuration(d))return x.value}return null}
function hourlyAt(data,time){return data.hourly.find(p=>time>=new Date(p.startTime)&&time<new Date(p.endTime))}
function phase(hour,v){if(hour===v.startHour)return"ARRIVAL";if(hour===18)return"OPEN";if(hour===22)return"PRIME";if(hour===24)return"MIDNIGHT";if(hour===v.endHour)return"CLOSE";return""}
function assess(data,v,key){const hours=eventHours(v,key),g=data.grid;const max=(series,map=x=>x)=>Math.max(...hours.map(h=>map(gridAt(series,h))||0));const rain=max(g.probabilityOfPrecipitation),thunder=max(g.probabilityOfThunder),gust=max(g.windGust,kmhToMph),heat=Math.max(...hours.slice(0,3).map(h=>cToF(gridAt(g.heatIndex,h))||cToF(gridAt(g.temperature,h))||0));if(thunder>=C.thresholds.thunderHigh)return{label:"LIGHTNING CONCERN",detail:"Thunder potential peaks near "+round(thunder)+"%",class:"danger"};if(rain>=C.thresholds.rainHigh)return{label:"RAIN INTERRUPTIONS",detail:"Rain chance peaks near "+round(rain)+"%",class:"danger"};if(thunder>=C.thresholds.thunderCaution)return{label:"WATCHING STORMS",detail:"Thunder potential peaks near "+round(thunder)+"%",class:"caution"};if(rain>=C.thresholds.rainCaution)return{label:"SHOWERS POSSIBLE",detail:"Rain chance peaks near "+round(rain)+"%",class:"caution"};if(gust>=C.thresholds.gustCautionMph)return{label:"GUSTY",detail:"Forecast gusts near "+round(gust)+" mph",class:"caution"};if(heat>=C.thresholds.hotArrivalF)return{label:"HOT ARRIVAL",detail:"Feels-like temperature near "+round(heat)+"°",class:"caution"};return{label:"FAVORABLE",detail:"No major weather signal in the event window",class:"favorable"}}
async function loadSelected(force=false){state.forecast="loading";updateSystem();try{const data=await getForecast(selectedVenue,force);if(isEvent(selectedVenue,selectedDate))renderHourly(data);else renderDaily(data);state.forecast="current"}catch(e){$("forecast-content").innerHTML='<div class="loading-card data-failed">FORECAST SIGNAL LOST · '+e.message+"</div>";$("forecast-meta").textContent="UPDATE FAILED";state.forecast="failed"}updateSystem()}
function renderHourly(data){const hours=eventHours(selectedVenue,selectedDate),g=data.grid,a=assess(data,selectedVenue,selectedDate);$("forecast-title").textContent="EVENT-NIGHT TIMELINE";$("forecast-meta").textContent="NWS DIGITAL FORECAST · "+selectedVenue.short+" POINT";$("event-status").className="event-status "+a.class;$("event-status").innerHTML="<span>EVENT STATUS</span><strong>"+a.label+"</strong><small>"+a.detail+"</small>";
 const rows=[["PHASE",(h,i)=>phase(selectedVenue.startHour+i,selectedVenue),"phase"],["CONDITION",h=>hourlyAt(data,h)?.shortForecast||"—"],["TEMP °F",h=>round(cToF(gridAt(g.temperature,h)))],["DEWPOINT °F",h=>round(cToF(gridAt(g.dewpoint,h)))],["FEELS °F",h=>round(cToF(gridAt(g.heatIndex,h))||cToF(gridAt(g.temperature,h)))],["WIND MPH",h=>compass(gridAt(g.windDirection,h))+" "+safe(round(kmhToMph(gridAt(g.windSpeed,h))))],["GUST MPH",h=>safe(round(kmhToMph(gridAt(g.windGust,h))))],["RAIN %",h=>safe(round(gridAt(g.probabilityOfPrecipitation,h)))],["THUNDER %",h=>safe(round(gridAt(g.probabilityOfThunder,h)))]];
 const head="<thead><tr><th>ELEMENT</th>"+hours.map(h=>"<th>"+fmt(h,{hour:"numeric"})+"</th>").join("")+"</tr></thead>";
 const body=rows.map(([label,fn,base])=>"<tr><td>"+label+"</td>"+hours.map((h,i)=>{const v=fn(h,i),n=+v,risk=(label.includes("RAIN")&&n>=C.thresholds.rainHigh)||(label.includes("THUNDER")&&n>=C.thresholds.thunderHigh)?"high-risk":(label.includes("RAIN")&&n>=C.thresholds.rainCaution)||(label.includes("THUNDER")&&n>=C.thresholds.thunderCaution)?"risk":base||"";return'<td class="'+risk+'">'+(label==="CONDITION"?String(v).replace(/Thunderstorms?/i,"T-Storms").slice(0,16):v)+"</td>"}).join("")+"</tr>").join("");
 $("forecast-content").innerHTML='<table class="hourly-table">'+head+"<tbody>"+body+"</tbody></table>";
}
function renderDaily(data){$("forecast-title").textContent="NON-EVENT DAILY OUTLOOK";const day=data.daily.find(p=>dateKey(new Date(p.startTime))===selectedDate&&p.isDaytime),night=data.daily.find(p=>dateKey(new Date(p.startTime))===selectedDate&&!p.isDaytime),target=day||night;$("event-status").className="event-status";$("event-status").innerHTML="<span>EVENT STATUS</span><strong>NO EVENT CONFIGURED</strong><small>Daily planning view active</small>";if(!target){$("forecast-content").innerHTML='<div class="loading-card">DETAILED FORECAST NOT YET IN RANGE</div>';return}$("forecast-content").innerHTML='<div class="daily-focus"><div class="narrative"><span>FORECAST</span><strong>'+safe(target.shortForecast)+'</strong><p>'+safe(target.detailedForecast)+'</p></div><div><span>HIGH</span><strong>'+safe(day?.temperature)+"°</strong></div><div><span>LOW</span><strong>"+safe(night?.temperature)+"°</strong></div><div><span>RAIN</span><strong>"+safe(day?.probabilityOfPrecipitation?.value??night?.probabilityOfPrecipitation?.value)+"%</strong></div><div><span>WIND</span><strong>"+safe(day?.windSpeed??night?.windSpeed)+"</strong><span>"+safe(day?.windDirection??night?.windDirection)+"</span></div></div>"}
function presentWeather(p){return p.textDescription||p.presentWeather?.map(w=>w.rawString||w.weather).filter(Boolean).join(" ")||"—"}
async function loadObservations(){const results=await Promise.allSettled(C.stations.map(s=>request(API+"/stations/"+s.id+"/observations?limit=3")));let any=false;$("observation-rows").innerHTML=results.map((r,i)=>{const s=C.stations[i];if(r.status!=="fulfilled"||!r.value.features?.length)return'<article class="obs-row '+(s.primary?"primary":"")+'"><strong>'+s.id+"<small>"+s.label+'</small></strong><span class="data-failed">DATA UNAVAILABLE</span></article>';const p=r.value.features[0].properties,prior=r.value.features[1]?.properties||{},a=age(new Date(p.timestamp));if(a.level==="current")any=true;const t=cToF(p.temperature?.value),pt=cToF(prior.temperature?.value),trend=t!=null&&pt!=null&&Math.abs(t-pt)>=2?(t>pt?"↑":"↓"):"";return'<article class="obs-row '+(s.primary?"primary":"")+'"><strong>'+s.id+"<small>"+s.label+" · "+a.minutes+'M OLD</small></strong><span class="'+(a.level!=="current"?"data-"+a.level:"")+'">'+safe(round(t))+"° / "+safe(round(cToF(p.dewpoint?.value)))+'° <b class="trend '+(trend==="↑"?"up":"down")+'">'+trend+"</b></span><span>"+compass(p.windDirection?.value)+" "+safe(round(kmhToMph(p.windSpeed?.value)))+" MPH</span><span>"+safe(round(kmhToMph(p.windGust?.value)))+"</span><span>"+(p.visibility?.value==null?"—":round(mToMi(p.visibility.value))+"SM")+" / "+presentWeather(p)+"</span></article>"}).join("");state.observations=any?"current":results.some(r=>r.status==="fulfilled")?"stale":"failed";$("obs-state").textContent=state.observations.toUpperCase();updateSystem()}
const alertOrder=["Tornado Warning","Severe Thunderstorm Warning","Flash Flood Warning","Tornado Watch","Severe Thunderstorm Watch","Special Weather Statement","Flood Advisory"];
async function loadAlerts(){state.alerts="loading";updateSystem();try{const d=await request(API+"/alerts/active?point="+selectedVenue.latitude+","+selectedVenue.longitude),rank=e=>{const i=alertOrder.indexOf(e);return i<0?99:i},alerts=(d.features||[]).sort((a,b)=>rank(a.properties.event)-rank(b.properties.event)),top=alerts[0]?.properties;$("venue-alert").className="venue-alert "+(top?(top.event.includes("Warning")?"danger":"caution"):"");$("venue-alert").innerHTML=top?"<strong>"+top.event.toUpperCase()+" · "+selectedVenue.short+" INCLUDED</strong>":"<strong>NO ACTIVE NWS PRODUCTS FOR "+selectedVenue.short+"</strong>";$("alert-list").innerHTML=alerts.length?alerts.map(f=>'<article class="alert-item"><strong>'+f.properties.event+"</strong><p>"+(f.properties.headline||f.properties.description?.split("\n")[0]||"")+"</p></article>").join(""):'<article class="alert-item"><p>No active warnings, watches, advisories or statements include this venue point.</p></article>';$("alerts-state").textContent=alerts.length?alerts.length+" ACTIVE":"POINT CLEAR";state.alerts="current"}catch(e){$("venue-alert").className="venue-alert failed";$("venue-alert").innerHTML="<strong>ALERT STATUS UNAVAILABLE — THIS IS NOT AN ALL-CLEAR</strong>";$("alerts-state").textContent="UPDATE FAILED";state.alerts="failed"}updateSystem()}
function extractAfd(text){const lines=text.replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean);for(const key of["SHORT TERM","SYNOPSIS","DISCUSSION"]){const i=lines.findIndex(x=>x.toUpperCase().includes("."+key));if(i>=0){const s=lines.slice(i+1,i+8).join(" ").replace(/&&.*/,"").split(/(?<=[.!?])\s+/)[0];if(s.length>40)return{key,text:s.slice(0,430)}}}return{key:"DISCUSSION",text:lines.slice(0,8).join(" ").slice(0,430)}}
async function loadAfd(){try{const idx=await request(API+"/products/types/AFD/locations/MLB"),latest=idx["@graph"]?.[0];if(!latest?.id)throw new Error("No current MLB AFD");const p=await request(API+"/products/"+latest.id),h=extractAfd(p.productText||"");$("afd-headline").textContent=h.text;$("afd-meta").textContent=h.key+" · ISSUED "+(p.issuanceTime?fmt(new Date(p.issuanceTime),{hour:"numeric",minute:"2-digit"}):"UNKNOWN")+" · ORIGINAL FORECASTER WORDING";state.afd="current"}catch(e){$("afd-headline").textContent="Melbourne Area Forecast Discussion is temporarily unavailable.";$("afd-meta").textContent="SOURCE UPDATE FAILED";state.afd="failed"}updateSystem()}
const HHN_HOUSES=[
"Jack & Oddfellow: Chaos & Control","Cybergoria","INVASION: Alien Abduction","MADLANDS: Caged Cannibals","H.R. Bloodengutz Presents: A Halloween Fright-Tacular!","Sinners","Evil Dead Burn","Stranger Things 5","Hellraiser","Ozzy Osbourne: Prince of Darkness"
];
const norm=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function houseMatch(name){const n=norm(name);return HHN_HOUSES.find(h=>{const k=norm(h);return n===k||n.includes(k)||k.includes(n)})}
function waitTrend(name,wait){const previous=waitHistory[name];if(!Number.isFinite(wait)||!Number.isFinite(previous))return{icon:"N/A",class:"na"};const diff=wait-previous;if(Math.abs(diff)<5)return{icon:"→",class:"steady"};return diff>0?{icon:"↑ +"+diff,class:"up"}:{icon:"↓ "+Math.abs(diff),class:"down"}}
async function getUniversalParkId(){const data=await request("https://api.themeparks.wiki/v1/destinations");const destinations=data.destinations||data;for(const d of destinations){if(!/universal orlando/i.test(d.name||""))continue;const park=(d.parks||d.children||[]).find(p=>/universal studios florida/i.test(p.name||""));if(park)return park.id}throw new Error("Universal Studios Florida entity not found")}
async function loadWaitTimes(){
 if(selectedVenue.id!=="universal")return;
 state.waits="loading";$("wait-state").textContent="REFRESHING LIVE FEED";updateSystem();
 try{
  const parkId=await getUniversalParkId(),data=await request("https://api.themeparks.wiki/v1/entity/"+parkId+"/live"),live=data.liveData||[];
  const found=new Map();
  live.forEach(item=>{const canonical=houseMatch(item.name);if(canonical)found.set(canonical,item)});
  const rows=HHN_HOUSES.map(name=>{const item=found.get(name),status=String(item?.status||"UNKNOWN").toUpperCase(),raw=item?.queue?.STANDBY?.waitTime,wait=Number.isFinite(raw)?raw:null,open=status==="OPERATING"||status==="OPEN",updated=item?.lastUpdated?new Date(item.lastUpdated):null;return{name,item,status,open,wait,updated}});
  rows.sort((a,b)=>{const group=x=>x.open&&Number.isFinite(x.wait)?0:x.open?1:2;return group(a)-group(b)||(group(a)===0?b.wait-a.wait:a.name.localeCompare(b.name))});
  let rank=0;
  $("wait-list").innerHTML=rows.map(row=>{const ranked=row.open&&Number.isFinite(row.wait),trend=waitTrend(row.name,row.wait);if(ranked)rank++;const waitText=ranked?row.wait+" MIN":"N/A",statusText=row.open?"OPEN":row.status==="UNKNOWN"?"NO RELIABLE DATA":row.status.replaceAll("_"," "),updated=row.updated?fmt(row.updated,{hour:"numeric",minute:"2-digit"}):"SOURCE TIME N/A";return'<article class="wait-row '+(!ranked?"unranked":"")+'"><strong class="wait-rank">'+(ranked?"#"+rank:"—")+'</strong><span class="house-name">'+row.name+"</span><strong class=\"wait-value\">"+waitText+'</strong><span class="wait-trend '+trend.class+'">'+trend.icon+'</span><span class="wait-status">'+statusText+"<small>UPDATED "+updated+"</small></span></article>"}).join("");
  const snapshot={};rows.forEach(r=>{if(Number.isFinite(r.wait))snapshot[r.name]=r.wait});waitHistory=snapshot;
  const reliable=rows.filter(r=>r.open&&Number.isFinite(r.wait)).length;
  $("wait-state").textContent=reliable?reliable+" RELIABLE · 5 MIN REFRESH":"N/A · NO RELIABLE POSTED WAITS";
  state.waits=reliable?"current":"stale";
 }catch(e){
  $("wait-list").innerHTML=HHN_HOUSES.map(name=>'<article class="wait-row unranked"><strong class="wait-rank">—</strong><span class="house-name">'+name+'</span><strong class="wait-value">N/A</strong><span class="wait-trend na">N/A</span><span class="wait-status">FEED UNAVAILABLE<small>VERIFY IN UNIVERSAL APP</small></span></article>').join("");
  $("wait-state").textContent="WAIT-TIME FEED UNAVAILABLE";state.waits="failed";
 }
 updateSystem();
}
;